"""Autogenerated by scripts/build_v2_allowlist.py — do not edit by hand."""
from __future__ import annotations
import html
from urllib.parse import urlsplit, urlunsplit


def norm(url: str) -> str:
    """Normalize a URL for v2-allowlist comparison."""
    if not url:
        return ""
    s = html.unescape(url.strip())
    try:
        p = urlsplit(s)
    except Exception:
        return s
    path = p.path.rstrip("/") or "/"
    return urlunsplit(("https", p.netloc.lower(), path, p.query, ""))


V2_ALLOWLIST: frozenset[str] = frozenset({
    'https://announce.incheon.go.kr/citynet/jsp/sap/SAPGosiBizProcess.do?command=searchList&flag=gosiGL&svp=Y&sido=ic',
    'https://cis.seoul.go.kr/TotalAlimi_new/Notice.action',
    'https://gb.go.kr/Main/open_contents/section/gunsul/page.do?mnu_uid=6046&',
    'https://infose.info21c.net/common/finder/index?findStr=%EA%B8%B0%EC%88%A0%EC%A0%9C%EC%95%88',
    'https://newtech.gg.go.kr/main/pblanNow.do',
    'https://singisul.daegu.go.kr/index.do?menu_id=00000880',
    'https://state.gwd.go.kr/portal/bulletin/notification',
    'https://www.ansan.go.kr/www/common/bbs/selectPageListBbs.do?bbs_code=WWW13',
    'https://www.anseong.go.kr/portal/saeol/gosiList.do?mId=0501040000',
    'https://www.asan.go.kr/main/cms?no=131',
    'https://www.asan.go.kr/main/cms?no=257',
    'https://www.bisco.or.kr/news/news01',
    'https://www.bmc.busan.kr/board/list2.do?boardId=BBS_0000001&menuCd=DOM_000000101001001000&contentsSid=25&cpath=',
    'https://www.bucheon.go.kr/site/program/board/basicboard/list?boardtypeid=26754&menuid=148002003002',
    'https://www.busan.go.kr/gunsul/gunsulopen01',
    'https://www.busan.go.kr/nbgosi',
    'https://www.calspia.go.kr/portal/cnpp/viewCnppCnmtRcrPsu.do',
    'https://www.cheonan.go.kr/cop/bbs/BBSMSTR_000000000462/selectBoardList.do',
    'https://www.cheonan.go.kr/kor/sub02_03_01.do',
    'https://www.cheongju.go.kr/cheongwon/contents.do?key=1311',
    'https://www.cheongju.go.kr/cheongwon/selectBbsNttList.do?bbsNo=514&key=1309&integrDeptCode=000100251',
    'https://www.cheongju.go.kr/heungdeok/contents.do?key=1891',
    'https://www.cheongju.go.kr/heungdeok/selectBbsNttList.do?bbsNo=512&key=1889&integrDeptCode=000100230',
    'https://www.cheongju.go.kr/sangdang/contents.do?key=1020',
    'https://www.cheongju.go.kr/sangdang/selectBbsNttList.do?bbsNo=511&key=1018&integrDeptCode=000100186',
    'https://www.cheongju.go.kr/seowon/contents.do?key=1196',
    'https://www.cheongju.go.kr/seowon/selectBbsNttList.do?bbsNo=513&key=1194&integrDeptCode=000100209',
    'https://www.cheongju.go.kr/www/contents.do?key=281',
    'https://www.cheongju.go.kr/www/selectBbsNttList.do?bbsNo=510&key=280&integrDeptCode=000100101',
    'https://www.chungbuk.go.kr/road/selectBbsNttList.do?bbsNo=292&key=1975',
    'https://www.chungbuk.go.kr/www/contents.do?key=422',
    'https://www.chungnam.go.kr/cnportal/province/province/list.do?menuNo=500487',
    'https://www.chungnam.go.kr/construction/main/contents.do?menuNo=1600016',
    'https://www.daegu.go.kr/index.do?menu_id=00000854&servletPath=%2Findex.do',
    'https://www.daegu.go.kr/index.do?menu_id=00000855',
    'https://www.daejeon.go.kr/drh/drhGosiList.do?gosigbn=A&menuSeq=1908',
    'https://www.daejeon.go.kr/gun/GunNoticeList.do?menuSeq=397',
    'https://www.dcco.kr/web/board/list.do?mId=113',
    'https://www.ekr.or.kr/planweb/board/list.krc?contentUid=402880317cc0644a017cc0c22f2800f0&boardUid=402880317cc0644a017cc463cec202be&contentUid=402880317cc0644a017cc0c22f2800f0&subPath=',
    'https://www.ex.co.kr/',
    'https://www.gb.go.kr/Main/page.do?mnu_uid=6789&&BD_CODE=gosi_notice',
    'https://www.gbgs.go.kr/open_content/ko/page.do?mnu_uid=2159',
    'https://www.gbgs.go.kr/open_content/ko/page.do?mnu_uid=2160&',
    'https://www.gc.go.kr/portal/saeol/gosi/list.do?seCode=01&mId=1202180100',
    'https://www.gccity.go.kr/portal/saeol/gosi/list.do?mId=0301040000',
    'https://www.gg.go.kr/bbs/board.do?bsIdx=469&menuId=1547',
    'https://www.gh.or.kr/gh/bid-announcement.do',
    'https://www.gimhae.go.kr/03360/00023/00024.web',
    'https://www.gimhae.go.kr/03360/00023/00029.web',
    'https://www.gjcity.go.kr/portal/saeol/gosi/list.do?mId=0202010000',
    'https://www.gm.go.kr/pt/user/nftcBbs/BD_selectNftcBbsList.do?q_nftcBbsCode=1001&q_nftcBbsMgtno=&q_searchKeyTy=&q_searchVal=&q_rowPerPage=&q_currPage=1&q_sortName=&q_sortOrder=',
    'https://www.gmcc.co.kr/board.es?mid=a10402000000&bid=0018',
    'https://www.goyang.go.kr/www/link/BD_notice.do',
    'https://www.gwangju.go.kr/build/boardList.do?boardId=BD_0000000156&pageId=build9',
    'https://www.gwangju.go.kr/contentsView.do?pageId=www791',
    'https://www.gyeongnam.go.kr/board/list.gyeong?boardId=BBS_0000020&menuCd=DOM_000000704001000000',
    'https://www.gyeongnam.go.kr/index.gyeong?menuCd=DOM_000000135003009001',
    'https://www.hscity.go.kr/www/gosi/BD_selectGosiList.do?q_cp=1&q_notAncmtSeCode=04&q_notAncmtMgtNo=&q_sc=&q_depNm=&q_sv=&q_rowPerPage=10&q_currPage=1&q_sortName=&q_sortOrder=',
    'https://www.i-sh.co.kr/main/lay2/program/S1T294C295/www/brd/m_241/list.do?multi_itm_seqs=1,2,4,8,16,32,64,128,256,512',
    'https://www.ih.co.kr/main/customer/notification/notice.jsp',
    'https://www.ih.co.kr/main/sale_lease/board/shopping_notice.jsp',
    'https://www.incheon.go.kr/jonggeon/JO020101',
    'https://www.jeonbuk.go.kr/board/list.jeonbuk?boardId=BBS_0000012&menuCd=DOM_000000103001002001&contentsSid=841&cpath=',
    'https://www.jeonnam.go.kr/J0203/boardList.do?menuId=jeonnam0203000000',
    'https://www.jpdc.co.kr/open/news/notice.htm',
    'https://www.kwater.or.kr/news/sub01/noti01List.do?s_mid=105&brdId=KO27',
    'https://www.lh.or.kr/index.do',
    'https://www.molit.go.kr/brocm/USR/BORD0201/m_15109/BRD.jsp',
    'https://www.molit.go.kr/drocm/USR/BORD0201/m_16064/BRD.jsp',
    'https://www.molit.go.kr/irocm/USR/BORD0201/m_15643/BRD.jsp',
    'https://www.molit.go.kr/srocm/USR/BORD0201/m_13078/BRD.jsp',
    'https://www.molit.go.kr/srocm/USR/BORD0201/m_19696/LST.jsp',
    'https://www.molit.go.kr/wrocm/USR/BORD0201/m_15959/BRD.jsp',
    'https://www.nyj.go.kr/main/185',
    'https://www.osan.go.kr/portal/saeol/gosi/list.do?mId=0302010000',
    'https://www.pyeongtaek.go.kr/pyeongtaek/saeol/gosi/list.do?seCode=01&mid=0401020000',
    'https://www.sdco.or.kr/board.es?mid=a10601020000&bid=0007',
    'https://www.sejong.go.kr/bbs/R0071/list.do',
    'https://www.sejong.go.kr/prog/publicNotice/kor/sub02_0303/C1/list.do',
    'https://www.seongnam.go.kr/notice/publicNotice.do?menuIdx=1000499&returnURL=%2Fmain.do',
    'https://www.seosan.go.kr/www/contents.do?key=1258',
    'https://www.seosan.go.kr/www/selectBbsNttList.do?bbsNo=97&key=1256',
    'https://www.seoul.go.kr/news/news_notice.do',
    'https://www.sisul.or.kr/open_content/main/govern30/contract/specific.jsp',
    'https://www.sisul.or.kr/open_content/main/introduce/notice.jsp',
    'https://www.suwon.go.kr/sw-www/www04/www04-06.jsp',
    'https://www.uiwang.go.kr/UWKORINFO0701',
    'https://www.yongin.go.kr/home/yiNw/yiNwInfo/yiNwInfo01/yiNwInfo01_01.jsp;jsessionid=sV1oqCCKq3qsIrTZaZ3vmVaaWNaTwhFuYTFOTzRUVrpSoddkbTPBHoh8iXNRbDXu.yonginwas_servlet_engine3',
})
