"""Generate scrapers/_v2_allowlist.py from src/data/regions.json.

The allowlist is the set of normalized source URLs that scrapers/run_all.py
is permitted to crawl and write into notices_v2. Anything outside this set
is skipped (entries) and dropped (post-scrape notices).

Re-run after every edit to version2.xlsx + build_regions_json.py.
"""
from __future__ import annotations
import html
import json
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

ROOT = Path(__file__).resolve().parent.parent
REGIONS = ROOT / "src" / "data" / "regions.json"
OUT = ROOT / "scrapers" / "_v2_allowlist.py"

def norm(url: str) -> str:
    if not url:
        return ""
    s = html.unescape(url.strip())
    try:
        p = urlsplit(s)
    except Exception:
        return s
    path = p.path.rstrip("/") or "/"
    return urlunsplit(("https", p.netloc.lower(), path, p.query, ""))

def main() -> None:
    data = json.loads(REGIONS.read_text(encoding="utf-8"))
    urls: set[str] = set()
    for r in data:
        for sub in r.get("subEntities", []):
            for src in sub.get("sources", []):
                u = src.get("url")
                if u:
                    urls.add(norm(u))

    sorted_urls = sorted(urls)
    body = [
        '"""Autogenerated by scripts/build_v2_allowlist.py — do not edit by hand."""',
        "from __future__ import annotations",
        "import html",
        "from urllib.parse import urlsplit, urlunsplit",
        "",
        "",
        "def norm(url: str) -> str:",
        '    """Normalize a URL for v2-allowlist comparison."""',
        "    if not url:",
        '        return ""',
        "    s = html.unescape(url.strip())",
        "    try:",
        "        p = urlsplit(s)",
        "    except Exception:",
        "        return s",
        '    path = p.path.rstrip("/") or "/"',
        '    return urlunsplit(("https", p.netloc.lower(), path, p.query, ""))',
        "",
        "",
        "V2_ALLOWLIST: frozenset[str] = frozenset({",
    ]
    for u in sorted_urls:
        body.append(f"    {u!r},")
    body.append("})")
    body.append("")

    OUT.write_text("\n".join(body), encoding="utf-8")
    print(f"Wrote {OUT} with {len(sorted_urls)} normalized URLs")

if __name__ == "__main__":
    main()
